server:
  port: 8001

spring:
  application:
    # spring 应用名称，同时也作为微服务的名称
    name: cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///demo_01
    username: root
    password: 3375
  http:
    converters:
      preferred-json-mapper: jackson

# actuator config
management:
  endpoints:
    web:
      # choose endpoints be exposed
      exposure:
        include: ["health","info"]
  endpoint:
    health:
      # sometimes may need more details
      show-details: when_authorized

# endpoint-info message
info:
  application:
    # ${} can be used to get value in spring
    name: ${spring.application.name}
    port: ${server.port}
  build:
    # @@ can be used to set value when compile via maven
    artifactId: @project.artifactId@
    version: @project.version@
  metadata:

mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.kun.**.entity
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    # eureka 体系下的实例名称，默认为 <host>:<application.name>:<port>
    instance-id: ${spring.application.name}-${server.port}
    # 可以在 eureka 服务管理页面显示实例的 ip
    prefer-ip-address: true
    # 续租间隔，心跳周期
    lease-renewal-interval-in-seconds: 30
    # 定义服务该服务实例的失效时间，默认 90s
    # 超出该时限而未续约的服务，在 eureka-server 清理进程（默认周期 60s 的定时任务）启动时会被剔除
    lease-expiration-duration-in-seconds: 90
    # 实例元数据，可以修改原生元数据，也可以自定义，如修改 zone 从 defaultZone -> beijing
    # metadata-map
  client:
    # eureka-server 地址，可以配置多个 zone，每个 zone 下可以配置多个 eureka-server 地址，逗号分隔
    # 默认注册地址为：defaultZone: http://localhost:8761/eureka/
    # 启用注册中心安全认证的时候地址需要为 http://<username>:<password>@<host>:<port>/<suffix>
    # 通常需要配置上所有的 eureka-server
    service-url:
      defaultZone: http://eureka-server-one:8761/eureka/,http://eureka-server-two:8762/eureka/

